<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Licenes_ui-checkbox-state-hover</name>
   <tag></tag>
   <elementGuidId>f6bde4de-6987-4012-9109-b38e17de8fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-bizagi-wp-project-plan-content-dashboard']/div/div/div/div[2]/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ui-checkbox-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check6272158</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-checkbox-state-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-bizagi-wp-project-plan-content-dashboard&quot;)/div[@class=&quot;bz-wp-wrapper&quot;]/div[@class=&quot;ui-bizagi-layout&quot;]/div[@class=&quot;ui-bizagi-component-loading&quot;]/div[@class=&quot;desktop ui-bizagi-container ui-bizagi-container-form ui-widget-content  ui-bizagi-rendering-mode-execution&quot;]/div[@class=&quot;ui-bizagi-container-form-wrapper-animation&quot;]/div[@class=&quot;ui-bizagi-main-section ui-bizagi-section-behavior&quot;]/div[@class=&quot;ui-bizagi-section-border&quot;]/div[@class=&quot;ui-bizagi-container clearfix ui-bizagi-container-panel&quot;]/div[@class=&quot;ui-bizagi-container clearfix ui-bizagi-container-group ui-drop-shadow ui-lifted  cssClassContainer&quot;]/div[@class=&quot;ui-bizagi-container-group-wrapper ui-widget-content&quot;]/div[@class=&quot;ui-bizagi-container clearfix ui-bizagi-container-horizontal&quot;]/div[@class=&quot;ui-bizagi-container clearfix ui-bizagi-container-panel  ui-panel-area&quot;]/div[@class=&quot;ui-bizagi-render ui-corner-all ui-widget-content ui-bizagi-render-display-normal&quot;]/div[@class=&quot;ui-bizagi-control&quot;]/div[@class=&quot;ui-bizagi-control-wrapper&quot;]/div[@class=&quot;ui-bizagi-render-control     ui-bizagi-render-display-block ui-bizagi-render-boolean-yesno control-required&quot;]/div[@class=&quot;ui-checkbox&quot;]/label[@class=&quot;ui-checkbox-state-hover&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-bizagi-wp-project-plan-content-dashboard']/div/div/div/div[2]/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/label</value>
   </webElementXpaths>
</WebElementEntity>
